name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  versions-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set update script executable
        run: "chmod +x update_versions.sh"
        shell: bash
      
      - name: Execute update script
        run: "./update_versions.sh"
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: versions
          path: versions.txt
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: versions
        - shell: bash
        run: "source versions.txt"
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: fredericpinaud/cloudimage:latest